# Experiments on synthetic data (BJ-RNN baseline)

In [2]:
%load_ext autoreload
%autoreload 2

Required imports

In [3]:
import numpy as np

import seaborn as sns
from matplotlib import pyplot as plt
%matplotlib inline

from utils.train_synthetic import run_synthetic_experiments
from utils.results import get_joint_coverages, get_interval_widths, plot_timeseries

In [4]:
BASELINES = ['BJRNN']

# Static noise profile

In [ ]:
for baseline in ['BJRNN']:
    for seed in range(5):
        run_synthetic_experiments(experiment='static', 
                                  baseline=baseline,
                                  n_train = 2000,
                                  retrain_auxiliary=True,
                                  recompute_dataset=True,
                                  save_model=True, 
                                  save_results=True,
                                  rnn_mode='RNN',
                                  seed=seed)

Training BJRNN
Training dataset 0
Epoch:  0 | train loss: 8.5794
Epoch:  50 | train loss: 7.9333
Epoch:  100 | train loss: 9.0237
Epoch:  150 | train loss: 10.7468
Epoch:  200 | train loss: 9.4355
Epoch:  250 | train loss: 7.3767
Epoch:  300 | train loss: 8.4498
Epoch:  350 | train loss: 9.0975
Epoch:  400 | train loss: 9.6869
Epoch:  450 | train loss: 9.5128
Epoch:  500 | train loss: 9.1163
Epoch:  550 | train loss: 9.1743
Epoch:  600 | train loss: 9.5061
Epoch:  650 | train loss: 10.4087
Epoch:  700 | train loss: 9.0968
Epoch:  750 | train loss: 9.6103
Epoch:  800 | train loss: 8.4667
Epoch:  850 | train loss: 11.1679
Epoch:  900 | train loss: 12.3933
Epoch:  950 | train loss: 10.2442
Training dataset 1
Epoch:  0 | train loss: 9.5642
Epoch:  50 | train loss: 9.3675
Epoch:  100 | train loss: 9.0132
Epoch:  150 | train loss: 8.5782
Epoch:  200 | train loss: 8.5565
Epoch:  250 | train loss: 9.4200
Epoch:  300 | train loss: 11.1462
Epoch:  350 | train loss: 10.1542
Epoch:  400 | train lo

**Joint coverage** 

Prints mean joint coverage across the horizon (mean±std of 5 random seeds, with each row indicating a different dataset)

In [ ]:
for baseline in ['BJRNN']:
    print(baseline)
    coverages_mean, coverages_std = get_joint_coverages(baseline, 'static', seeds=range(5))
    
    for m, s in zip(coverages_mean, coverages_std):
        print('{:.1f} \\(\\pm\\) {:.1f}\\%'.format(m, s))
    print()

BJRNN
99.9 \(\pm\) 0.2\%
99.8 \(\pm\) 0.1\%
99.6 \(\pm\) 0.4\%
100.0 \(\pm\) 0.1\%
99.9 \(\pm\) 0.2\%



In [ ]:
for baseline in ['BJRNN']:
    print(baseline)
    widths_mean, widths_std = get_interval_widths(baseline, 'static', seeds=range(5))
    
    print(widths_mean)
    print(widths_std)

    print()

BJRNN
[30.69915917 26.15965366 26.13531172 26.40026501 27.57770923]
[11.66782423  2.34472132  2.24957157  1.50863427  2.22065518]



# Time-dependent noise profile

Training procedure for CF-RNN/MQ-RNN/DP-RNN baselines (for 5 different seeds):

In [ ]:
for baseline in ['BJRNN']:
    for seed in range(5):
        run_synthetic_experiments(experiment='time_dependent', 
                                  baseline=baseline,
                                  n_train = 2000,
                                  retrain_auxiliary=True,
                                  save_model=True, 
                                  save_results=True,
                                  rnn_mode='RNN',
                                  seed=seed)

Training BJRNN
Training dataset 0
Epoch:  0 | train loss: 13.9886
Epoch:  50 | train loss: 12.6675
Epoch:  100 | train loss: 11.1967
Epoch:  150 | train loss: 13.9567
Epoch:  200 | train loss: 14.0799
Epoch:  250 | train loss: 15.6307
Epoch:  300 | train loss: 15.0454
Epoch:  350 | train loss: 14.9318
Epoch:  400 | train loss: 12.5476
Epoch:  450 | train loss: 11.7732
Epoch:  500 | train loss: 12.5791
Epoch:  550 | train loss: 12.7417
Epoch:  600 | train loss: 14.9488
Epoch:  650 | train loss: 10.7527
Epoch:  700 | train loss: 13.7926
Epoch:  750 | train loss: 10.8014
Epoch:  800 | train loss: 10.9499
Epoch:  850 | train loss: 14.3753
Epoch:  900 | train loss: 12.3114
Epoch:  950 | train loss: 13.3183
Training dataset 1
Epoch:  0 | train loss: 25.6105
Epoch:  50 | train loss: 24.3140
Epoch:  100 | train loss: 20.3995
Epoch:  150 | train loss: 24.3123
Epoch:  200 | train loss: 23.1713
Epoch:  250 | train loss: 25.0532
Epoch:  300 | train loss: 23.0256
Epoch:  350 | train loss: 21.3599
E

**Joint coverage**

Prints mean joint coverage across the horizon (mean±std of 5 random seeds, with each row indicating a different dataset)

In [ ]:
for baseline in ['BJRNN']:
    print(baseline)
    coverages_mean, coverages_std = get_joint_coverages(baseline, 'time_dependent', seeds=[0,1,2,3])
    
    for m, s in zip(coverages_mean, coverages_std):
        print('{:.1f} \\(\\pm\\) {:.1f}\\%'.format(m, s))
    print()

BJRNN
99.3 \(\pm\) 0.5\%
96.8 \(\pm\) 2.0\%
93.7 \(\pm\) 1.9\%
90.0 \(\pm\) 2.3\%
83.2 \(\pm\) 0.6\%



**Interval widths**

Prints the baseline; mean±std of interval width across horizons; rows denote the noise configuration and columns the random seed. 

In [ ]:
for baseline in ['BJRNN']:
    print(baseline)
    widths_mean, widths_std = get_interval_widths(baseline, 'time_dependent', seeds=[0,1,3,4])
    
    print(widths_mean)
    print(widths_std)
    print()

BJRNN
[27.90853504 27.51841832 32.80742456 35.54742906 39.38776248]
[2.08241808 2.07214946 1.8318299  1.98028232 2.64290742]

